### PR TITLE
Remove zend-stdlib dependency

### PR DESCRIPTION
**Pull request by Trainmaster**
### Description

Fixes https://github.com/PHPOffice/PHPWord/issues/1256

### Checklist:

- [x] I have run `composer run-script check --timeout=0` and no errors were reported
- [ ] The new code is covered by unit tests (check build/coverage for coverage report)
- [ ] I have update the documentation to describe the changes

### CODE REVIEW

**Comment by troosan** [comment]
@Trainmaster a better solution would be to use PhpOffice\Common\Text:: isUTF8 instead.
I'll see if can un-deprecate it (@Progi1984?).

**Comment by Progi1984** [comment]
👌 with that.

**Comment by Trainmaster** [comment]
@troosan I changed it to `PhpOffice\Common\Text:: isUTF8`.

**Comment by JamesB7** [comment]
I think the is_string check is important: preg_match will return true for non-strings, such as integers. (Yes, this surprised me too. Hurrah for PHP?)

Without the is_string check, callers of isUTF8 (such as toUTF8) may pass through non-string values without converting them to string (such as utf8_encode does).

**Comment by troosan** [comment]
I create a PR in https://github.com/PHPOffice/Common/pull/19 to modify the method

**Comment by Progi1984** [comment]
Merged ;)

**Pull request merged**
