### PR TITLE
Implement PageBreak for odt writer

### PR DESCRIPTION
**Pull request by cookiekiller**
Implemented page break for odt writer, works great.

### CODE REVIEW

**Comment by cookiekiller** [comment]
I use it as it is, I added it using composer to my project extending phpword.

**Comment by cookiekiller** [comment]
@Progi1984 I proposed and tested this. This patch is in use for some time now! I'd suggest to merge it.

**Comment by Progi1984** [comment]
@cookiekiller Could you add some unit tests ?

**Comment by troosan** [comment]
@cookiekiller I could not update your branch (readonly) so I created a new one (PR #1206)

**Pull request closed without merging**
