### PR TITLE
Prevented fatal errors when opening corrupt files or "doc" files

### PR DESCRIPTION
**Pull request by mmcev106**
### Description

This prevents fatal exceptions when trying to load corrupt files or old "doc" files, allowing applications to catch the exception and fail gracefully.

Fixes # (issue) - None. I just fixed it without reporting an issue.

### Checklist:

- [x] My CI is :green_circle:
- [x] I have covered by unit tests my new code (check build/coverage for coverage report)
- [ ] I have updated the [documentation](https://github.com/PHPOffice/PHPWord/tree/master/docs) to describe the changes
- [x] I have updated the [changelog](https://github.com/PHPOffice/PHPWord/blob/master/docs/changes/2.x/2.0.0.md)

### CODE REVIEW

**Comment by mmcev106** [comment]
I'm looking into the coding standard failures.

**Comment by mmcev106** [comment]
I think we're good to go now (guessing the `deploy` failure is not something I should look into).

**Review by everaldofilho — APPROVED** [review]

**Comment by mmcev106** [comment]
@everaldofilho, thanks for the approval.  Any idea when this might get merged?  If there are any further changes you'd like me to make, please ask.

**Comment by Progi1984** [comment]
@mmcev106 Could you update the changelog ?

**Comment by mmcev106** [comment]
@Progi1984, the changelog has been updated.

**Review by Progi1984 — APPROVED** [review]

**Pull request merged**
