### PR TITLE
Word2007 Reader : Added support for Comments

### PR DESCRIPTION
**Pull request by Progi1984**
### Description

Word2007 Reader : Added support for Comments

Superseeds #2161. Thanks @shaedrich.

### Checklist:

- [x] I have run `composer run-script check --timeout=0` and no errors were reported
- [x] The new code is covered by unit tests (check build/coverage for coverage report)
- [x] I have updated the documentation to describe the changes

### CODE REVIEW

**Comment by shaedrich** [comment]
Awesome! Happy, that this is picked up! Looking forward to its release :)

**Comment by Progi1984** [comment]
@shaedrich It's merged for the next 1.2.0 version.

**Comment by shaedrich** [comment]
This is awesome. Thanks you for implementing it!

**Comment by Progi1984** [comment]
Thanks for the PR. And sorry for the late implementation.

**Comment by shaedrich** [comment]
Better late then never&mdash;no harm done.

**Pull request merged**
