### PR TITLE
Bump to travis php version

### PR DESCRIPTION
**Pull request by michaelachrisco**
Small code coverage on section footers.

### CODE REVIEW

**Comment by michaelachrisco** [comment]
Looks like String is a protected word in php 7.0. Ill add in a patch (String -> PHPWordString).

**Comment by michaelachrisco** [comment]
Two bugs:
* Methods with the same name as their class will not be constructors in a future version of PHP; PclZip has a deprecated constructor

* Methods with the same name as their class will not be constructors in a future version of PHP; mPDF has a deprecated constructor

Looks like either these packages need to be updated or fixed of PHP 7 errors. Down the rabbit hole I go.

**Comment by Haringat** [comment]
You should revert 72927e3.
The package tecnick.com/tcpdf is abandoned and replaced by tecnickcom/tcpdf so the former dependency list was correct.

**Comment by michaelachrisco** [comment]
@Haringat Ill take a stab at this later today. I have a feeling that it wont be as simple as requiring the correct library and off we go. I have no idea if the two libraries can work with PHP 7.0. tecnickcom/tcpdf Does not have a travis build by the look of it

**Comment by michaelachrisco** [comment]
I believe I am going to let 7.0 fail at the moment (unless someone else has a better option?), and make the test pass. I'll go down the rabbit hole on some of the dependencies to fix the 7.0 issue on their side and then push to this branch.

**Comment by RomanSyroeshko** [comment]
Partially duplicate of #658.

As regards coverage. I made couple experiments and found that `@codeCoverageIgnore` annotation sometimes has no effect. I have no idea why. For example, you can see that `\PhpOffice\PhpWord\Element\Footnote` has four methods, two of which are marked with `@codeCoverageIgnore`. In the same time the report says that coverage is 50% (2 of 4 methods are covered). That looks strange, because two methods should be ignored at all.

I think we should consider upgrading PHPUnit in the future. We use very old one, and it may have some bugs. Thanks for pointing this out.

**Comment by michaelachrisco** [comment]
Thanks @RomanSyroeshko I was stuck for a while on some of the tests and why they were not passing. Going into the parent repos was a rabbit hole. Glad to see someone working on 7.0 coverage.

**Pull request closed without merging**
