### PR TITLE
Added support for Floating Table Positioning (tblpPr)

### PR DESCRIPTION
**Pull request by anrikun**
… docx writing is implemented for now.

### CODE REVIEW

**Comment by troosan** [comment]
@anrikun your branch is read-only so I cannot update it, can you please change it so maintainers can commit on it?

**Comment by anrikun** [comment]
@troosan I've just added you as a collaborator. Is that what you needed? Sorry I don't known the right procedure to make a branch writeable.

**Comment by troosan** [comment]
@anrikun it seems that's not enough. can you try the following?
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by troosan** [comment]
@anrikun I had not accepted the invitation, now it's OK

**Comment by anrikun** [comment]
@troosan Thanks for the link!

**Pull request merged**
