### PR TITLE
Added PhpOffice\Common as requirement

### PR DESCRIPTION
**Pull request by Progi1984**
@RomanSyroeshko : I wait for your validation :)

### CODE REVIEW

**Comment by Progi1984** [comment]
That will help you with the support of PHP7 (String => Text).

**Comment by michaelachrisco** [comment]
Looks like we are solving the same issue. I like your naming better. Whatever works for php 7.0. Ill remove my CommonString if this branch gets merged but keep travis settings.

**Comment by huglester** [comment]
@RomanSyroeshko please review this pull request

**Comment by flogr** [comment]
Will there be a bugfix release for this one? I really need this, but 0.13.* isn't released yet...

**Comment by kimsreng** [comment]
how soon will this be released?

**Comment by temirfe** [comment]
@RomanSyroeshko it's been half year and still the problem has not been solved, come on man!

**Comment by jarederaj** [comment]
It looks like this has been resolved in the develop branch.

```
{
    "require": {
       "phpoffice/phpword": "dev-develop"
    }
}
```

https://github.com/PHPOffice/PHPWord/issues/732

**Comment by kehh** [comment]
This is included in https://github.com/PHPOffice/PHPWord/releases/tag/v0.13.0

**Comment by BonnieDoug** [comment]
How does it work? I mean for upgrading from previous versions? I just keep getting 

        Fatal error: Class 'PhpOffice\PhpWord\Shared\String' not found in .../blah/vendor/phpoffice/phpword/src/PhpWord/Style/AbstractStyle.php on line 164

**Comment by maxgorovenko** [comment]
Class PhpOffice\PhpWord\Shared\String was renamed for compatibility with php7

**Comment by Progi1984** [comment]
v0.13.0 is ever released and fixes bugs : https://github.com/PHPOffice/PHPWord/releases/tag/v0.13.0

**Pull request closed without merging**
