### PR TITLE
Renamed String to SharedString

### PR DESCRIPTION
**Pull request by benjiw87**
Renamed PhpOffice\PhpWord\Shared\String to PhpOffice\PhpWord\Shared\SharedString, as String is a special class name as of PHP7

### CODE REVIEW

**Comment by Progi1984** [comment]
Or use PHPOffice\Common ;)

**Comment by huglester** [comment]
Hello @RomanSyroeshko ,

any chance this will be accepted?

We need to run one project on php7, and only this library is stopping us.

Thank you!

**Comment by ozilion** [comment]
PHP 7 is out and I think there should be a quick fix release, right?

**Comment by huglester** [comment]
I do wait for this very much!

**Comment by fisharebest** [comment]
The tests are failing because the test cases have not been renamed.  I think all you need to do is:

1. rename the file `tests/PhpWord/Shared/StringTest.php` to `tests/PhpWord/Shared/SharedStringTest.php`
2. rename `String` to `SharedString` within it.

**Comment by gomax** [comment]
We need this PR too. The last issue breaks our project on php7..

**Comment by fisharebest** [comment]
I guess this PR is superceded by #698

**Comment by Progi1984** [comment]
Or #658

**Comment by RomanSyroeshko** [comment]
Guys, thank you very much for voting. I'll try to handle it this weekend.

**Comment by RomanSyroeshko** [comment]
Resolved in scope of #658.

**Pull request closed without merging**
