### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by wandrewchan**
remove abandoned zend-escaper, replace with laminas

### CODE REVIEW

**Comment by stephanvierkant** [comment]
You also changedf some other files. Can you explain those changes?

**Comment by internalsystemerror** [comment]
the latest version of laminas/laminas-escaper requires PHP >= 5.6

**Comment by stephanvierkant** [comment]
> the latest version of laminas/laminas-escaper requires PHP >= 5.6

Of course it does. PHP 5.6 is very very old.

**Comment by stephanvierkant** [comment]
> the latest version of laminas/laminas-escaper requires PHP >= 5.6

What's the point?

**Comment by internalsystemerror** [comment]
U asked what the other changes were for. As far as I can see, those changes are removing the support for PHP < 5.6. That's the only point here.

**Comment by stephanvierkant** [comment]
I mean files like `src/PhpWord/Escaper/AbstractEscaper.php`

**Comment by liborm85** [comment]
Why is upgraded minimal php version? This is BC break. You can use `"laminas/laminas-escaper": "^2.2",`.

And PR contains other irrelevant changes in AbstractEscaper.php.
PR is wrong.

**Comment by stephanvierkant** [comment]
Yes, in theory this might be a BC break. But it has been upgraded to a PHP version that hasn't got support for years now. I don't consider removing support for EOL-versions a BC-break.

**Comment by wandrewchan** [comment]
Actually I was trying to replace with laminas as what @tacman, but it was failed. And I found that zend-escaper has deprecated, but it still works. So this merge is discard and closed.

**Comment by liborm85** [comment]
I'm adding compatibility with PHP 7.4 and PHP 8.0 in PR https://github.com/PHPOffice/PHPWord/pull/1946, was necessary fix travis and scrutinizer. So also migrate to Laminas, commit: https://github.com/PHPOffice/PHPWord/pull/1946/commits/f2516b08b146da9b2be66326bb36d6f54fe56781

**Comment by stephanvierkant** [comment]
That would be (at least) the third attempt to replace zend by laminas. And again, that PR contains other changes as well.

**Comment by liborm85** [comment]
Without next changes it is not possible to test whether it works in travis.

**Comment by tacman** [comment]
My PR was a one-line fix, and it gets rid of the warning that shows up every time.  Was there a problem with that PR?  Yes, at the moment the deprecated version still works, but there's no reason to keep it.

PHP 5 is dead, dead, dead.  Anyone using it should upgrade.  That's a different PR, of course.

**Pull request closed without merging**
