### PR TITLE
Added support for linebreaks <br /> in Shared\Html::addHtml()

### PR DESCRIPTION
**Pull request by anrikun**

### CODE REVIEW

**Comment by Progi1984** [comment]
Need some unit tests :)

**Comment by bernemann** [comment]
I would appreciate this PR, is it enough to add some sample code to PhpWordTest.php?

**Comment by troosan** [comment]
@anrikun Is it possible your branch is read-only (did you uncheck the "Allow edits from maintainers" checkbox)? I cannot commit on it.

**Comment by troosan** [comment]
since this PR seems to be read-only, I created a new PR #1217 and added missing unit tests

**Pull request closed without merging**
