### PR TITLE
PHP 8.1 Support for addPreserveText

### LINKED ISSUE #2220: PHP 8.1 Support  for addPreserveText
### Describe the Bug

If I use php 8.1 this code doesn't work:

### Steps to Reproduce

Please provide a code sample that reproduces the issue.

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$phpWord = new \PhpOffice\PhpWord\PhpWord();
$section = $phpWord->addSection();
$section->addTitle("test", 1);

$footer = $section->addFooter();
$footer->addPreserveText('{PAGE} / {NUMPAGES}');
	    
header("Content-Type: application/vnd.openxmlformats-officedocument.wordprocessing‌​ml.document");
header('Content-Disposition: attachment; filename=test.docx');
$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
$objWriter->save("php://output");
```

### Expected Behavior

The same output that I have if I use PHP 7.4

### Current Behavior

preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated
 in vendor\phpoffice\phpword\src\PhpWord\Element\PreserveText.php at line 63
    public function __construct($text = null, $fontStyle = null, $paragraphStyle = null)
        ...
        $matches = preg_split('/({.*?})/', $this->text, null, PREG_SPLIT_DELIM_CAPTURE | PREG_SPLIT_NO_EMPTY);

-> preg_split parameter #3 needs to be -1 not null.

During XMLWriter->save(...): Uncaught yii\base\ErrorException: Return type of PhpOffice\PhpWord\Shared\XMLWriter::writeAttribute($name, $value) should either be compatible with XMLWriter::writeAttribute(string $name, string $value): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor\phpoffice\phpword\src\PhpWord\Shared\XMLWriter.php:174

-> add #[\ReturnTypeWillChange] attribute

### Context

Please fill in your environment information:

- PHP Version: 8.1
- PHPWord Version:  0.18.3

### PR DESCRIPTION
**Pull request by cscrewsandcaptains**
### Description

PHP 8.1 Support for addPreserveText

Fixes #2220 

### Checklist:

- [ ] I have run `composer run-script check --timeout=0` and no errors were reported (** scripts not run with PHP 8.1 (without my changes!) **)
- [ ] The new code is covered by unit tests (**not necessary**)
- [ ] I have updated the documentation to describe the changes  (**not necessary**)

### CODE REVIEW

**Comment by rtek** [comment]
This along with all the other php8.1 related deprecations need to be merged.

**Comment by garethellis36** [comment]
@PowerKiKi You helped to merge, tag, and release #2187 which was another PHP 8.1 fix. Is there any chance you might be able to help with this one, and also #2292 and #2272? Or @Progi1984 ?

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @cscrewsandcaptains for the contribution

Thansk @garethellis36 for the ping.

**Comment by garethellis36** [comment]
Thanks folks, any chance of a tagged release please? :)

**Comment by natsimhan** [comment]
I also wait after this release (v0.18.4 ? ^^) to validate the migration to PHP8.1 of all my application ;)

**Comment by PowerKiKi** [comment]
released as [1.0.0](https://github.com/PHPOffice/PHPWord/releases/tag/1.0.0)

**Pull request merged**
