### PR TITLE
rename 'Object' classes to 'ObjectElement' (php 7.2 compatibility)

### PR DESCRIPTION
**Pull request by SailorMax**
If name is not very good, now easier to find all require places to rename ;)

### CODE REVIEW

**Comment by SailorMax** [comment]
Scrutinizer said "Failed", but I can't see what's the problem?

**Comment by troosan** [comment]
@SailorMax not a big fan of the name ObjectElement, it is too different from all other elements.
What about OLEObject?

**Comment by SailorMax** [comment]
I think you better know.
I don't know internal structure of PHPWord and used `ObjectElement` as name similar to `AbstractElement`.
If it looks like `OLEObject`, you can rename it :)

**Comment by troosan** [comment]
still need https://github.com/tecnickcom/TCPDF/pull/74 to be fully PHP 7.2 compatible

**Comment by stevechilds** [comment]
@troosan - Has your fix been pushed into the main branches yet as the 7.2 "Object" class bug is causing us issues on our new Ubuntu 18.04 setup, which uses PHP 7.2 ?

I've tried 0.14, which is what we were on, which fails and even using "phpoffice/phpword": "dev-master" failed to resolve the issue.

**Pull request merged**
