### PR TITLE
To support PreserveText inside sub container

### PR DESCRIPTION
**Pull request by bhattnishant**
### Description

if we use PreserveText inside table or special characters, issue fixed
Relavent
https://stackoverflow.com/questions/33070424/phpword-cannot-add-preservetext-in-section

### Checklist:

- [ ] I have run `composer run-script check --timeout=0` and no errors were reported
- [x] The new code is covered by unit tests (check build/coverage for coverage report)
- [ ] I have updated the documentation to describe the changes

### CODE REVIEW

**Comment by troosan** [comment]
@bhattnishant Can you fix the failing test please?

**Comment by tidalgo22** [comment]
@troosan If you don't mind me asking. When can the v.0.17.0 be release? I'm hoping to get this fix asap. Thank you

**Comment by troosan** [comment]
> @troosan If you don't mind me asking. When can the v.0.17.0 be release? I'm hoping to get this fix asap. Thank you

I'm hoping to release it still this month, I've been quite busy these last weeks!

**Comment by tidalgo22** [comment]
> > @troosan If you don't mind me asking. When can the v.0.17.0 be release? I'm hoping to get this fix asap. Thank you
> 
> I'm hoping to release it still this month, I've been quite busy these last weeks!

I hope it would be this month. 
Thank you and have great day.

**Pull request merged**
