### PR TITLE
Added support for fixed tableLayout, allowing to use fixed width columns in tables

### PR DESCRIPTION
**Pull request by ekopach**
Added the function to fix the width of columns in tables, when text very long and without delimiters.

- [x] I have run `composer check` and no errors were reported
- [ ] The new code is covered by unit tests
- [ ] I have update the documentation to describe the changes

### CODE REVIEW

**Comment by troosan** [comment]
@ekopach actually, this is already implemented in #841, which has not yet been merged.

**Comment by ekopach** [comment]
Oh, thanks. Sorry, I have not seen.

**Comment by samimussbach** [comment]
@troosan I could test and review one of the PRs as we have the same issue. Which one do you prefer?

**Comment by troosan** [comment]
@samimussbach I don't really have a preference. This solution seems simpler, as only 2 values are possible and 1 the default value, I guess just a boolean is enough.
Both PR are missing unit test, doc, ... though :-S
It would also be nice to immediately implement the reader for it.

**Comment by troosan** [comment]
@samimussbach please check out the following #1281

**Comment by samimussbach** [comment]
You where faster than me, nice. Will check.

**Pull request closed without merging**
