### PR TITLE
Add whitespace between Tag CleanUp

### PR DESCRIPTION
**Pull request by philippfrenzel**
Added a white clean between Tags -> as lists are normally rendered with a double newline inbetween

### CODE REVIEW

**Comment by troosan** [comment]
I guess a better way would be to set
```php
$dom->preserveWhiteSpace = false;
```
I've added this in the current development branch (with an additional optional param to keep backward compatibility)

**Comment by philippfrenzel** [comment]
Hi @troosan ,

thanks for adding the hint with preserveWhiteSpace -> what about the addition of the <i>-Tag?

Thanks Philipp

**Comment by troosan** [comment]
@philippfrenzel that has already been done in de development branch

**Comment by philippfrenzel** [comment]
ok - thanks for the update - you are doing a great job!

**Pull request closed without merging**
