### PR TITLE
Add support for various missing features in HTML Writer

### PR DESCRIPTION
**Pull request by oleibman**
### Description

Implement a number of features implemented in PhpWord,
but not yet supported in PhpWord HTML Writer.

    1. Use css @page and page declarations for sections.
    2. Wrap sections in div, with page break before each (except first).
    3. Add ability to specify generic fallback font for html (documentation change).
    4. Add ability to specify handling of whitespace in html (documentation change).
       Currently, Word writer preserves space but HTML writer does not.
    5. Support for Language, both for document overall and individual text elements.
    6. Support for PageBreak for HTML (currently only PDF is supported).
    7. Support for Table Border style, color, and size.
    8. Support for empty paragraphs (Word writer permits, browsers generally suppress).
    9. Default paragraph style should apply to all paragraphs, as well as class Normal.
    10. Paragraph style should support line-height.
    11. Paragraph style should support indentation.
    12. Paragraph style should support page-break-before.
    13. Paragraph style should not specify margin-top/bottom when spacing is null.

Testing change from Pull Request 1771 is included here, but was
merged after my fork.

Fixes # (issue)

### Checklist:

- [x] I have run `composer run-script check --timeout=0` and no errors were reported
- [x] The new code is covered by unit tests (check build/coverage for coverage report)
- [x] I have updated the documentation to describe the changes

### CODE REVIEW

**Comment by mussbach** [comment]
There is quite a bunch of valuable stuff in that PR but as it is huge it is hard to review. Could you perhaps split this into multiple smaller PRs? It would be a pity if this PR would rot

**Comment by oleibman** [comment]
It would be a lot of work to separate things. I would sort of like some assurance from the maintainer that the current state is a problem before I undertook it. That being said, I think I *might* be able to split it in 3  (PR is over a year old, so details aren't exactly fresh in my mind):
- Work that just has to be done - bugs, design flaws - steps 1, 2, 6, 8, 9, and 13 (maybe).
-  Missing support for paragraph style - steps 10, 11, 12, and 13 (maybe - I think it's more important than the others).
- New features and other missing support (steps 3, 4, 5, 7).

I realize you can't tell from this description how much would be left to review for each part. Neither can I ("not exactly fresh") without further study. Nevertheless, do you think what I describe above might be sufficient for your purposes?

**Comment by mussbach** [comment]
I perfectly understand that this would be a lot of effort. I am not in the position to give any assurance so I fear we have to wait for some reaction

**Comment by troosan** [comment]
That's indeed one big PR, with various fixes/improvements/features.

I'll try to review this for the next minor release

**Comment by oleibman** [comment]
Thanks.

**Comment by Krato** [comment]
Is this PR being to nbe implemented?

**Comment by Progi1984** [comment]
@oleibman Thank your for your contribution. Could you rebase your PR ?

**Comment by oleibman** [comment]
@Progi1984 I am not quite as conversant with git/github as I should be. The fact that there are now a number of merge conflicts, and that the main branch has changed from develop to master, make me a little uneasy doing anything to this PR. Would the following steps accomplish what you want instead?
- rename my existing repository
- make a fresh fork of PhpOffice/PhpWord
- clone my new fork
- make the same changes as in this PR
- after local testing, push the new PR

If that looks like an okay plan, I can probably have something for you within a week. If it's not an okay plan, please tell me how to proceed instead.

**Comment by oleibman** [comment]
I have completed a dry run where I applied my changes to the master version, and edited them according to the new standards (square brackets rather than array function for example - thank you @Progi1984 and @PowerKiKi, I can tell how painful a job that must have been just  from my need to do it in a small number of members, but it was definitely time to do it). I am glad to report that I was able to get successful results for both the existing and the new unit tests. I want to do some more testing, but I can probably start working on a new PR in earnest in a day or two.

One question for now. I use the "check" script defined in composer.json for the project, and that failed because it invokes phpcs, which is not required by composer.json. I manually added it for my testing. Is it okay to proceed with that as a dev requirement, or should the check script be changed?

**Comment by oleibman** [comment]
@Progi1984 Rebased version is now available as PR #2343. I was, as I feared, unable to make a second fork, so I just deleted my fork, which caused this ticket to be closed, which I was planning to do anyhow.

**Pull request closed without merging**
