### PR TITLE
Added the ability to enable gridlines and axislabels on charts

### PR DESCRIPTION
**Pull request by FrankMeyer**
Added options 'showAxisLabels', 'showGridX', 'showGridY' to charts style element.
Added appropriet set and get methods.
Those options can be testet in Sample_32_Charts.php, but they are set to false for now.
Default output of that sample is not changed.

### CODE REVIEW

**Comment by okrauth** [comment]
Hi, We are also looking at implementing the showAxisLabel to a chart style but it looks like that code was pulled. Any chance that we might see an implementation in a future release? 

Thanks

**Comment by okrauth** [comment]
Any chance to add the function "Add Data Labels" to Pie charts?

**Comment by FrankMeyer** [comment]
@okrauth: I`m not sure, for Pie Charts it is not working at the moment, maybe you can unpack a word doc with a Pie-Chart where the labels were created directly in Word. Then search for that labels in the xml files. Then you will see what you have to add to the PHPWord code to generate the correct XML Parts for PieChart labels. The Pie-Chart behaves somewhat different.

**Comment by betocantu93** [comment]
How to actually do this? Can't get it to work. any snippet?

**Comment by FrankMeyer** [comment]
@betocantu93 
see my changes in samples/Sample_32_Chart.php
or are you interested in the question of okrauth?

**Comment by betocantu93** [comment]
Im making several charts, like 300, so I need to label, use grids, and titles, I couldn't find a way to do it... Tried everything... 
On Mar 30, 2016 11:36 AM, Frank Meyer <notifications@github.com> wrote:@betocantu93 
see my changes in samples/Sample_32_Chart.php
or are you interested in the question of okrauth?

**Comment by betocantu93** [comment]
Line charts only, I need to add some labels and a grid, with axis labels

**Comment by okrauth** [comment]
@FrankMeyer : I unpacked a docx did a comparison and noticed that in order to add a leyend to a pie chart one needs to add the following code to the xml chat.xml document:

<c:legend><c:legendPos val="r"/><c:layout/><c:overlay val="0"/></c:legend>

Not sure how to accomplish this (which document to edit in the php library... can you point me in the right direction>

**Comment by FrankMeyer** [comment]
@okrauth: The charts are contructed in the file PhpWord/Writer/Word2007/Part/Chart.php.
For the other chart types the labels were added to the axis, but in case of a PieChart there are no axis.
So I would gues that the legend must be added in the function writePlotArea(XMLWriter $xmlWriter) in Chart.php. Maybe you should have a look in which xml elements the <c:legend> element is embedded.

**Comment by okrauth** [comment]
Thank you. I will check.

**Comment by FrankMeyer** [comment]
then you should add the legend part in this function: private function writeChart(XMLWriter $xmlWriter)
just after $this->writePlotArea($xmlWriter);

**Comment by okrauth** [comment]
@FrankMeyer  Got it... thanks

**Comment by phpdave** [comment]
I'm looking to add x and y axis labels,grid lines w/ amounts, and series w/ names.  Has this been implemented or because of the failed travis and scrutinzer checks it wasn't implemented?

**Comment by FrankMeyer** [comment]
The checks have not run correctly at that time, I just don't have the permissions to rerun travis and scrutinizer. They may succeed.

**Comment by phpdave** [comment]
FYI I've added some comments on how to get data labels options and axis options to be outputted here https://github.com/PHPOffice/PHPWord/issues/957

**Comment by scalco19** [comment]
help add Show Value in Piechart

`$xmlWriter->writeRaw(' <c:dLbl><c:extLst><c:ext><c:showVal val="1"/></c:ext></c:extLst></c:dLbl>');`



I'm not successful

**Comment by diggamies** [comment]
@scalco19 You should read @phpdave 's thread #957 ! If you already read it try following in _src/PhpWord/Writer/Word2007/Part/Chart.php_ in the writeSeries() method:

`$xmlWriter->startElement('c:dLbls');`
`$xmlWriter->writeRaw('<c:showLegendKey val="0"/><c:dLblPos val="outEnd"/><c:showVal val="1"/><c:showCatName val="0"/><c:showSerName val="0"/><c:showPercent val="0"/><c:showBubbleSize val="0"/>');`
`$xmlWriter->endElement(); // </c:dLbls>`

Works like a charm for me, but I am using $chartOptions as mentioned in #957

**Comment by troosan** [comment]
other features in #957

**Pull request merged**
