### PR TITLE
PHP7 Update - Renamed String class to SharedString

### PR DESCRIPTION
**Pull request by publiux**
PHP7 now reserves the class name String. PHPWord utilizes String as a class name, thus PHPWord presently does not work with PHP7. This PR renames the class to SharedString and updates it usage through the library and in the tests.

### CODE REVIEW

**Comment by publiux** [comment]
This build is failing because of mpdf.  mpdf is still using the old constructor style that is not suitable for PHP7. A fix was pulled into mpdf's development branch ( https://github.com/mpdf/mpdf/issues/68 ) but has not yet been tagged and thus is not pulled in via composer package.

**Comment by publiux** [comment]
I have updated composer.json to pull dev-development for mpdf, which has merged the constructor fix for PHP7. In the future, once the fix is pulled into a release tag, we need to change the composer.json to a stable version. Hopefully, this won't take too long.

**Comment by RomanSyroeshko** [comment]
Partially resolved in scope of #658.

**Comment by Faryshta** [comment]
what does this need to be merged?

**Comment by RomanSyroeshko** [comment]
Some thoughts.

mPDF 6.1 requires PHP 5.4+ while PHPWord - PHP 5.3.3+.

So, first of all #355 should be resolved.

**Pull request closed without merging**
