### PR TITLE
[experiment] Bump to PHP 7.0

### PR DESCRIPTION
**Pull request by TomasVotruba**
I remember you want to bump all PHPOffice libs to PHP 7.0, 
so I'm testing if Rector can handle that.

### CODE REVIEW

**Comment by troosan** [comment]
did you check the develop_v1.0 branch?

**Comment by TomasVotruba** [comment]
No, I just used the main branch.

**Comment by troosan** [comment]
Because I started this (dropping support for php 5.x) in that branch ;-)

**Comment by TomasVotruba** [comment]
Oh :D
Could you link PR?

**Comment by KazuAlex** [comment]
> Could you link PR?

https://github.com/PHPOffice/PHPWord/pull/1545 ;)

**Comment by TomasVotruba** [comment]
There are no PHP changes. Check this PR :)

**Comment by TomasVotruba** [comment]
Closing for lack of feedback

**Pull request closed without merging**
