### PR TITLE
TemplateProcessor->setImageValue()

### LINKED ISSUE #708: PHPWord 0.12.1 setImageValue - templateprocessor add image to docx
I was looking for a solution to add image. I read a lot of articles, I only found suitable solutions for older versions. Changing and finalized the decision to get the code.
Let us proceed to change the file TemplateProcessor.php
public function __construct($documentTemplate)
{
//add to this function

```
$this->_countRels=100; //start id for relationship between image and document.xml
```

}

public function save()
{
//add to this function after $this->zipClass->addFromString('word/document.xml', $this->tempDocumentMainPart);

```
if($this->_rels!="")
{
    $this->zipClass->addFromString('word/_rels/document.xml.rels', $this->_rels);
}
if($this->_types!="")
{
    $this->zipClass->addFromString('[Content_Types].xml', $this->_types);
}
```

}

//add function

```
public function setImg( $strKey, $img){
        $strKey = '${'.$strKey.'}';
        $relationTmpl = '<Relationship Id="RID" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/IMG"/>';

        $imgTmpl = '<w:pict><v:shape type="#_x0000_t75" style="width:WIDpx;height:HEIpx"><v:imagedata r:id="RID" o:title=""/></v:shape></w:pict>';

        $toAdd = $toAddImg = $toAddType = '';
        $aSearch = array('RID', 'IMG');
        $aSearchType = array('IMG', 'EXT');
        $countrels=$this->_countRels++;
        //I'm work for jpg files, if you are working with other images types -> Write conditions here
    $imgExt = 'jpg';
        $imgName = 'img' . $countrels . '.' . $imgExt;

            $this->zipClass->deleteName('word/media/' . $imgName);
            $this->zipClass->addFile($img['src'], 'word/media/' . $imgName);

            $typeTmpl = '<Override PartName="/word/media/'.$imgName.'" ContentType="image/EXT"/>';


            $rid = 'rId' . $countrels;
            $countrels++;
        list($w,$h) = getimagesize($img['src']);

 if(isset($img['swh'])) //Image proportionally larger side
 {
 if($w<=$h)
 {
    $ht=(int)$img['swh'];
    $ot=$w/$h;
    $wh=(int)$img['swh']*$ot;
    $wh=round($wh);
 }
 if($w>=$h)
 {
    $wh=(int)$img['swh'];
    $ot=$h/$w;
    $ht=(int)$img['swh']*$ot;
    $ht=round($ht);
 }
 $w=$wh;
 $h=$ht;
 }

if(isset($img['size']))
{
$w = $img['size'][0];
$h = $img['size'][1];           
}


            $toAddImg .= str_replace(array('RID', 'WID', 'HEI'), array($rid, $w, $h), $imgTmpl) ;
            if(isset($img['dataImg']))
            {
                $toAddImg.='<w:br/><w:t>'.$this->limpiarString($img['dataImg']).'</w:t><w:br/>';
            }

            $aReplace = array($imgName, $imgExt);
            $toAddType .= str_replace($aSearchType, $aReplace, $typeTmpl) ;

            $aReplace = array($rid, $imgName);
            $toAdd .= str_replace($aSearch, $aReplace, $relationTmpl);


        $this->tempDocumentMainPart=str_replace('<w:t>' . $strKey . '</w:t>', $toAddImg, $this->tempDocumentMainPart);
        //print $this->tempDocumentMainPart;



        if($this->_rels=="")
        {
            $this->_rels=$this->zipClass->getFromName('word/_rels/document.xml.rels');
            $this->_types=$this->zipClass->getFromName('[Content_Types].xml');
        }

        $this->_types       = str_replace('</Types>', $toAddType, $this->_types) . '</Types>';
                $this->_rels        = str_replace('</Relationships>', $toAdd, $this->_rels) . '</Relationships>';
}
```

//add function

```
function limpiarString($str) {
        return str_replace(
                array('&', '<', '>', "\n"), 
                array('&amp;', '&lt;', '&gt;', "\n" . '<w:br/>'), 
                $str
        );
}
```

//HOW TO USE???

```
$templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor('templ.docx');

//static zone
$templateProcessor->setValue('date', htmlspecialchars(date('d.m.Y G:i:s')));    
//$templateProcessor->cloneRow('NAME_IN_TEMPLATE', NUMBER_OF_TABLE_RECORDS);
$templateProcessor->cloneRow('AVTOR', 3);

//variant 1
//dynamic zone
$templateProcessor->setValue('AVTOR#1', htmlspecialchars('Garry'));
$templateProcessor->setValue('NAME#1', htmlspecialchars('Black Horse'));
$templateProcessor->setValue('SIZES#1', htmlspecialchars('100x300'));

/*$img = array(
        'src' => 'image.jpg',//path
    'swh'=>'350',//Image proportionally larger side
        'size'=>array(580, 280)
);*/
$templateProcessor->setImg('IMGD#1',array('src' => 'image.jpg','swh'=>'250'));

$templateProcessor->setValue('AVTOR#2', htmlspecialchars('Barry'));
$templateProcessor->setValue('NAME#2', htmlspecialchars('White Horse'));
$templateProcessor->setValue('SIZES#2', htmlspecialchars('200x500'));
$templateProcessor->setImg('IMGD#2',array('src' => 'image2.jpg','swh'=>'250'));

$templateProcessor->setValue('AVTOR#3', htmlspecialchars('Backer'));
$templateProcessor->setValue('NAME#3', htmlspecialchars('Another Side'));
$templateProcessor->setValue('SIZES#3', htmlspecialchars('120x430'));
$templateProcessor->setImg('IMGD#3',array('src' => 'image3.jpg','swh'=>'250'));
```

//variant 2

```
$templateProcessor->cloneRow('AVTOR', count($output['ID'])); 
        for($i=0;$i<count($output['ID']);$i++)
        {
            $templateProcessor->setValue('AVTOR'.'#'.($i+1), htmlspecialchars($output['AVTOR'][$i]));
            $templateProcessor->setValue('NAME'.'#'.($i+1), htmlspecialchars($output['PNAM'][$i]));
//GetImg($output['ID'][$i]) my function return image path
            $templateProcessor->setImg('IMGD'.'#'.($i+1), array('src'=>GetImg($output['ID'][$i]),'swh'=>'250'));
        }
```

//Save

```
$templateProcessor->saveAs('testTemplate.docx');
```

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30037116-phpword-0-12-1-setimagevalue-templateprocessor-add-image-to-docx?utm_campaign=plugin&utm_content=tracker%2F323108&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F323108&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #939: how add image place holder for MS word template?
how add image place holder for MS word template and how replace with php?
and how use loop in word template and PHP?

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39120451-how-add-image-place-holder-for-ms-word-template?utm_campaign=plugin&utm_content=tracker%2F323108&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F323108&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #1079: Insert image in TemplateProcessor
When I create a file through TemplateProcessor, it does not add images.

I would like a simple example of how to do this. The idea is to put a logo on the document that repeats on every page

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/46452705-insert-image-in-templateprocessor?utm_campaign=plugin&utm_content=tracker%2F323108&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F323108&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by SailorMax**
Allow to put images in templates.

Fixes #1079 
Fixes #939 
Fixes #708

### CODE REVIEW

**Comment by SailorMax** [comment]
This PR can solve next issues: #1079, #939 and #708

**Comment by FBnil** [comment]
But what about https://github.com/PHPOffice/PHPWord/pull/1084 ?

**Comment by SailorMax** [comment]
@FBnil 
Didn't saw it. Thanks.
My solution simpler -- without dimension convertings and without in template static image size per place. Second part is interesting!

You can choose the best for your self :)

**Comment by kaioken** [comment]
dude @SailorMax  just wanted to say thank you for this ;) really help me out with your branch

**Comment by SailorMax** [comment]
@kaioken 
you are welcome :)

**Comment by phuongnguyenle** [comment]
I need to approval this request to resolve the same issue. Could you please help us?

**Comment by grayback6192** [comment]
@SailorMax There's a problem with the variables thats being written from the PHPWord here's a snippet. 
```
//Creates Word File
$phpWord = new \PhpOffice\PhpWord\PhpWord();
$section = $phpWord->addSection();
$section->addText('${Test}');
$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
$objWriter->save('helloWorld.docx');
//Opens Word file
$templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor('helloWorld.docx');
$templateProcessor->setImageValue("Test","test.png");
$templateProcessor->saveAs("Test.docx");
```
**Here's the output**
image

Whenever it is written with phpWord, it won't change the variable with image. Works fine on setValue()

**Comment by olegmifle** [comment]
Hi all!
Can anybody help me to install this fork via composer.json?

**Comment by bigpws** [comment]
Just see the readme.md

**Comment by olegmifle** [comment]
@bigpws, as i see, it's describe installation of original package. I want use fork of SailorMax for using images in template.

**Comment by SailorMax** [comment]
@grayback6192 fixed.

**Comment by grayback6192** [comment]
@SailorMax thanks that worked, but there's another bug. Whenever the variables in one line, when the first value is being replaced by an image, the second variable disappears.
untitled

**Comment by marat-dimaev** [comment]
@olegmifle 

```
...
"require": {
        "phpoffice/phpword": "dev-template_processor__set_image_value",
},
"repositories": [
        {
            "type": "vcs",
            "url":  "https://github.com/SailorMax/PHPWord"
        }
]
...
```

**Comment by SailorMax** [comment]
@grayback6192 fixed.

**Comment by MatteoTagliabue** [comment]
Hi.
I ended up to this limitation working with templates, and your work is really great.
I need to use this feature for a project which and until the feature would be merged with the official PHPword package, I thought to use your fork.
Do you think that it would undergo major changes, or it would be safe to use it?

By the way, thanks for your amazing work! :)

**Comment by SailorMax** [comment]
@MatteoTagliabue Currently I have not any plans to change anything here. Only fixes if require.

**Comment by donriga** [comment]
Image not display

> //Creates Word File
$phpWord = new \PhpOffice\PhpWord\PhpWord();
$section = $phpWord->addSection();
$section->addText('${Test}');
$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
$objWriter->save('helloWorld.docx');
//Opens Word file
$templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor('helloWorld.docx');
$templateProcessor->setImageValue("Test","test.png");
$templateProcessor->saveAs("Test.docx");

`<w:document xmlns:ve="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml">
<w:body>
<w:p>
<w:pPr/>
<w:r>
<w:rPr/>
<w:t xml:space="preserve">
<w:pict>
<v:shape type="#_x0000_t75" style="width:504px;height:260px">
<v:imagedata r:id="rId7" o:title=""/>
</v:shape>
</w:pict>
</w:t>
</w:r>
</w:p>
<w:sectPr>
<w:pgSz w:orient="portrait" w:w="11905.511811024" w:h="16837.795275591"/>
<w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="720" w:footer="720" w:gutter="0"/>
<w:cols w:num="1" w:space="720"/>
</w:sectPr>
</w:body>
</w:document>`

**Comment by donriga** [comment]
This not work, image label not replaced
$templateProcessor->setImageValue("Test","test.png");

**Comment by SailorMax** [comment]
@donriga Work 2010 opens your Test.docx without problems and with picture.
On your screenshot editor output message about unknown fonts. May be problem not in my changes?
Can you try to open helloWorld.docx in your editor?

**Comment by donriga** [comment]
Open on MacOS (OpenOffice and Numbers)

**Comment by donriga** [comment]
On Google Drive word document also not display image

**Comment by donriga** [comment]
Cooool!!!! That work now!

**Comment by SailorMax** [comment]
@MatteoTagliabue Sorry, but I did feature update :) - support of template based image size + by default keep image aspect ratio.
Check it, please, on back compatibility.

**Comment by Skeptron** [comment]
Really great lib, good job guys, you really helped me out on a project! I have one question though - and sorry if it's a dumb one - but how can one set the size of the image? I couldn't find an exemple.

Thanks a lot!

**Comment by SailorMax** [comment]
@Skeptron 
On template side:
- `${search-image-pattern:[width]x[height]}`
- `${search-image-pattern:size=[width]x[height]}`
- `${search-image-pattern:width=[width]:height=[height]}`

On php side:
- `$templateProcessor->setImageValue('search-image-pattern', array('path' => 'path/to/logo.png', 'width' => 100, 'height' => 100));`

Brief documentation:
https://github.com/PHPOffice/PHPWord/pull/1170/commits/795965117f4821395ef2119e4d75967587ceab14

**Comment by Skeptron** [comment]
@SailorMax Thanks a lot, you rock!

**Comment by Skeptron** [comment]
Sorry to ask one more thing, but is there a way to keep original image size without having to code it? For some reason imported  images are always very small. I can fix this by manually setting their size, but it's quite a hasstle considering I have 160+ images to import. Is there any way to say "keep the orginal size when importing"? 

Thanks a lot

**Comment by SailorMax** [comment]
@Skeptron Currently you can get size by getimagesize() and setup it on php side. For better solution I need time :)

**Comment by ekohere** [comment]
why in mw project 
Call to undefined method PhpOffice\PhpWord\TemplateProcessor::setImageValue()
setImageValue not found in version versi 0.15.0 juga

**Comment by SailorMax** [comment]
@ekohere Possible because this commit is still unmerged with your 0.15

**Comment by ekohere** [comment]
what last version has support setImageValue?

**Comment by ekohere** [comment]
is there another way to insert images through the TemplateProcessor?

**Comment by SailorMax** [comment]
@ekohere While this pull request not merged, no one version contain it.
In theory you can merge it into your local repository, but I don't know how.

**Comment by scuben** [comment]
Would be great if that could be merged.

**Comment by ranolrandria** [comment]
hi, I'm using phpword to insert image with setImageValue, I don't know but the first image don't show and the file word is corrupt

**Comment by SailorMax** [comment]
> hi, I'm using phpword to insert image with setImageValue, I don't know but the first image don't show and the file word is corrupt

Can you share the sample of source document?

**Comment by Ifriqiya** [comment]
Hi, I have this code to add an image to a document, `$phpword->setImageValue('signature', $user->profile_photo_path);` but I get the error: 'Invalid image: profile-photos/RajPxHv0I6PgE3CtLas2oKXZhZFXSOGUjegbUURe.jpg'. What can I do to resolve this?

**Pull request merged**
