### PR TITLE
Fix parsing of textbreaks

### LINKED ISSUE #1274: Word2007 parser does not parse `<w:br/>` tags
This is:

- [X] a bug report
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

# Expected Behavior

IOFactory::load($source) should not modify source

### Current Behavior

On Windows 10 IOFactory::load($source) is removing all lines following a "soft return" or newline that is created with "Shift+Enter"

#### Example:
This is line one `<shift+enter>`
This is line two `<shift+enter>`
This is line three `<enter>`
This is line four

#### Becomes:
This is line one
This is line four

### Failure Information

Using TemplateProcessor to update a document template, and saving that document works as expected. later however when the documented is loaded using IOFactory::load($source), all lines following a soft return aren't existing.

### How to Reproduce
```php
$templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor($template);
$templateProcessor->setValue($keys, $values); 
$templateProcessor->saveAs($dest);

// Here the document is correct.

$document = \PhpOffice\PhpWord\IOFactory::load($dest);
$htmlWriter = new \PhpOffice\PhpWord\Writer\HTML($document);
$htmlWriter->save('broken_document.html');

// here the document is broken
```

```php
// this has the same broken result

$PHPWord = new \PhpOffice\PhpWord\Reader\Word2007();
$document = $PHPWord->load($template);
$htmlWriter = new \PhpOffice\PhpWord\Writer\HTML($document);
$htmlWriter->save('broken_document.html');
```

### Context

* PHP version: 7.2.0
* PHPWord version: 0.14.0

### PR DESCRIPTION
**Pull request by troosan**
### Description
When loading an existing word document, textbreaks are not being parsed

Fixes #1274

### Checklist:

- [x] I have run `composer check` and no errors were reported
- [x] The new code is covered by unit tests
- [x] I have update the documentation to describe the changes

### CODE REVIEW

**Comment by R-Benjamin** [comment]
Hi,

I did the test with the development branch and the problem is still present. 

If I put **<w:br/>**  in a string, the tag is not parsed.

Regards

**Comment by troosan** [comment]
@R-Benjamin what do you mean with

> If I put <w:br/> in a string, the tag is not parsed.

**Comment by R-Benjamin** [comment]
@troosan If I have: 

`$templateProcessor->setValue('txt_agent_detail_evalB#'.$i.'', "Test1 <w:br/> Test2");`

The word document will display: 

`"Test1 <w:br/> Test2"`

And not:

`"Test1
Test2"`

**Comment by troosan** [comment]
That's normal, you cannot pass xml to the template processor, it will be escaped.
Did you try to put `"Test1\nTest2"`

**Comment by R-Benjamin** [comment]
If I put `"Test1\nTest2"`, the word document display: `"Test1 Test2"`

It's not possible to make a line break with the templates?

**Pull request merged**
