### PR TITLE
Composer update

### LINKED ISSUE #865: ZF2 support is now broken.
Hi,

Good day.

I'm using PHPWord with ZF2 and PHP 7. So I've encountered issue https://github.com/PHPOffice/PHPWord/issues/736. Now I need to upgrade to v0.13.0. 

But I can't do that, because PHPWord requires 3 zendframework pacakges that are on version 2.4._. ZF2 version 2.5._ uses the same package but requires version 2.5.\* though.

```
"require": {
        "php": ">=5.7",
        "phpoffice/phpword": "v0.13.0",
        "zendframework/zendframework": "2.*"
    }
```

Any help/workaround will be much appreciated.

Cheers.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/37036089-zf2-support-is-now-broken?utm_campaign=plugin&utm_content=tracker%2F323108&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F323108&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jarrettj**
Use the latest zend framework 2.\* modules. Fixes #865.

### CODE REVIEW

**Comment by aight8** [comment]
Any news? I use zf3, and can't use this library because of dependency conflicts.

**Comment by marcomenzel** [comment]
What about using `^2.4` instead of `2.*`?
* It would not allow a downgrade to ZF >= 2.0 and <2.4
* Would stay PHP 5.3 compatible while using ZF 2.4
* You can use ZF 2.5 with "newer" PHP versions

**Comment by jarrettj** [comment]
Sounds good to me :) @marcomenzel

**Comment by jarrettj** [comment]
Hi,

Good day.

I'm not sure why this can't be merged? I'm not a composer pro. Will composer not install the proper dependencies if 2.* is used? 

Regards.
JJ

**Comment by jarrettj** [comment]
Hi @troosan, congrats on taking over the repo. And I know you have a ton of these requests. Is there any chance we could get this change in? It's pretty straight forward. (I think:) Thanks man.

**Comment by marcomenzel** [comment]
@jarrettj take a look at https://github.com/PHPOffice/PHPWord/pull/973#issuecomment-317111262

**Comment by troosan** [comment]
fixed with #1138

**Pull request closed without merging**
