### PR TITLE
move from "zendframework/zend-escaper" to  "laminas/laminas-escaper" 

### PR DESCRIPTION
**Pull request by DeyV**
move from "zendframework/zend-escaper" to  "laminas/laminas-escaper"  due to Zend Framework migration

### Description

Zend Framework repos are archived and unmaintaned. New name for this project is laminas
 

### Checklist:

- [x] I have run `composer run-script check --timeout=0` and no errors were reported
- [x] The new code is covered by unit tests (check build/coverage for coverage report)

### CODE REVIEW

**Comment by michaljusiega** [comment]
Let's finish this PR please, I am annoyed by migration messages.

**Comment by DeyV** [comment]
> Let's finish this PR please, I am annoyed by migration messages.

this is harder to do than I thought because laminas declare no support for not supported php versions. ( https://github.com/laminas/laminas-zendframework-bridge/pull/44 ) and at this moment I don't know - if its actual declaration, or not.

Maybe is't time to change list of supported php versions in PHPWord - but  I can't decide for the PHPWord team

**Comment by DeyV** [comment]
Fixed dependencies for php74

**Comment by repat** [comment]
Any holdups on this? How can we help? :)

**Comment by DeyV** [comment]
You have two options
- make some pressure on laminas team to add support for older php versions ( https://github.com/laminas/laminas-zendframework-bridge/pull/44#issuecomment-570621505 )
- change list of supported php versions in phpoffice

**Comment by diego-vieira** [comment]
@troosan this PR can be closed in favour of https://github.com/PHPOffice/PHPWord/pull/1916

**Comment by troosan** [comment]
#1946 already merged for this

**Pull request closed without merging**
