### PR TITLE
Add Support for Various Missing Features in HTML Writer

### LINKED ISSUE #2467: Bug while transforming html to word document with addHtml method.
### Describe the Bug

There is a bug in the phpword while transforming HTML to a Word document and it doesn’t recognize text-align: right. So we need to edit this file vendor/phpoffice/phpword/src/PhpWord/SimpleType/Jc.php and set const END = 'right'; instead of const END = 'end'; before running the transforming process.

### Steps to Reproduce
Here is an example of HTML code :

```
<p style="text-align:justify;"><strong>Poursuivre la gestion sur un compte dédié.</strong></p>
<p style="text-align:right;"><strong>Poursuivre la gestion sur un compte dédié.</strong></p>
<p style="text-align:right;">Frais de gestion de <strong>xx euros / mois HT</strong> facturés par Auto-planning.</p>
```
And php code: 
```
$phpWord = new \PhpOffice\PhpWord\PhpWord();
$section = $phpWord->addSection();
\PhpOffice\PhpWord\Shared\Html::addHtml($section, $ourHtmlCode, false, false);
$docFileName = "docFileNaame";
$objWriter   = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord);
$objWriter->save('/somePath/'. $docFileName);
$localDocFilePath = $tempPath . $docFileName;
$docContent       = $this->apiStorage->read($localDocFilePath);
$this->apiStorage->delete($localDocFilePath);
return $this->googleDriveStorage->write(
          'googleDiskFolderId',
          $docContent,
          [
               'name'     => $docFileName,
               'mimeType' => 'application/vnd.google-apps.document'
          ]
);
```
### Current Behavior
When I transform HTML code with align right to word doc. I do not have alignment in that place (For other align it works well)

### Context

- PHP Version: 7.2
- PHPWord Version: dev-master

### PR DESCRIPTION
**Pull request by oleibman**
This PR supersedes #1814 and #2343, which had become badly out of sync due to recent changes to the repository.

Implement a number of features implemented in PhpWord, but not yet supported in PhpWord HTML Writer.

1. Use css @page and page declarations for sections.
2. Wrap sections in div, with page break before each (except first).
3. Add ability to specify generic fallback font for html (documentation change).
4. Add ability to specify handling of whitespace in html (documentation change). Currently, Word writer preserves space but HTML writer does not.
5. Support for Language, both for document overall and individual text elements.
6. Support for PageBreak for HTML (currently only PDF is supported).
7. Support for Table Border style, color, and size.
8. Support for empty paragraphs (Word writer permits, browsers generally suppress).
9. Default paragraph style should apply to all paragraphs, as well as class Normal.
10. Paragraph style should support line-height.
11. Paragraph style should support indentation.
12. Paragraph style should support page-break-before.
13. Paragraph style should not specify margin-top/bottom when spacing is null.
14. Fix #2467 - text-align:right in html is not handled correctly.

### Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes # (issue)

### Checklist:

- [x] I have run `composer run-script check --timeout=0` and no errors were reported
- [x] The new code is covered by unit tests (check build/coverage for coverage report)
- [x] I have updated the documentation to describe the changes

### CODE REVIEW

**Comment by Progi1984** [comment]
@oleibman It's a wonderful work. Could you allow to commit on your repository ? I would like to complete your PR.

**Comment by oleibman** [comment]
@Progi1984 That would be great. However, I don't understand your question. When you ask "Could you allow to commit on your repository?", are you just asking me if it's okay to commit (in which case the answer is yes), or is there something I need to do in my repository to allow you to do what you need to do?

**Comment by Progi1984** [comment]
@oleibman Yes, could you add me as a collaborator ?

Doc : https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository#inviting-a-collaborator-to-a-personal-repository

**Comment by oleibman** [comment]
Done.

**Comment by Progi1984** [comment]
@oleibman I work on your PR the next week.

**Comment by oleibman** [comment]
Great! But ... I'm on vacation for a couple of weeks starting Wednesday, and am seriously considering not taking my computer with me. So, if you want to wait till I get back, I will let you know when I am available again.

**Comment by Progi1984** [comment]
@oleibman  I push some changes and wait for your return.

Have fun and rest.

**Comment by oleibman** [comment]
@Progi1984 I am back now, so please proceed. I noticed that this change also fixes a recent issue, so updated the description to say so (item 14 in my bullet list); no new code change is involved.

**Comment by Progi1984** [comment]
@oleibman My goal of the week : rebase the PR, check all modifications, add some unit tests and merge it. 💪

Please dont add or modify this branch.

**Comment by oleibman** [comment]
@Progi1984 Okay. Good luck.

**Comment by Progi1984** [comment]
(@oleibman Next time : Make one PR for each feature, it's more easy to review)

**Comment by oleibman** [comment]
@Progi1984 Apologies for the size of the PR. When I developed this one, it was modeled after similar work I had done for ODT and RTF writers, which were likewise comprised of many changes and installed that way. Also, I was pretty new to this so didn't realize this was problematic.

**Comment by oleibman** [comment]
@Progi1984 I have downloaded your latest set of changes and run some tests on my own. Everything appears to be working properly except for one minor problem. You changed Writer/HTML/Style/Paragraph line 99 to:
```php
$css[$this->getParentWriter() instanceof TCPDF ? 'text-indent' : 'margin-left'] = ((string) $inches) . 'in';
```
ParentWriter will be an instance of something like `PhpOffice\PhpWord\Writer\PDF\TCPDF`. However the TCPDF class which is being tested for instanceof is something like `PhpOffice\PhpWord\Writer\HTML\Style\TCPDF`. Adding the following to the beginning of Writer/HTML/Style/Paragraph will correct the problem (TCPDF ignores margin-left but honors text-indent):
```php
use PhpOffice\PhpWord\Writer\PDF\TCPDF;
```

**Comment by oleibman** [comment]
@Progi1984 Before I do something dumb - can I sync my master with PhpOffice without affecting your work on this PR?

**Comment by oleibman** [comment]
It appears that changing Writer/HTML/Element/AbstractElement so that parentWriter is of type `PhpOffice\PhpWord\Writer\HTML` rather than AbstractWriter will eliminate a lot of Phpstan errors without adversely affecting anything.

**Comment by oleibman** [comment]
@Progi1984 Downloaded the latest. After adapting some of my test scripts to new method names and/or locations, things are looking good. There are some things that are a little more difficult to code than they were, but I can still do them, so no big deal.

**Comment by Progi1984** [comment]
@oleibman I was going to contact you later today. I'll do some checking and merge later today.

**Comment by Progi1984** [comment]
:tada: @oleibman . Thanks for the contribution.

**Pull request merged**
