### PR TITLE
Added the possibility to read FormFields from Word2007 documents

### PR DESCRIPTION
**Pull request by vincentKool**
### Description

PHPWord had the option to create and write FormFields (checkbox, textinput and dropdown). This pull requests add the functionality to read those fields into the PHPWord model

### Bugfixes
This Pull request fixes Bug #2281 

### Checklist:

- [X] I have run `composer run-script check --timeout=0` and no errors were reported
- [X] The new code is covered by unit tests (check build/coverage for coverage report)
- [ ] I have updated the documentation to describe the changes

### CODE REVIEW

**Comment by KKSzymanowski** [comment]
I've tested this and can confirm it works, hoping this will get merged so I don't have to use a fork 🙂

For anyone who wants to get all the form fields in a document, I've came up with this recursive solution:
```php

/**
 * @param PhpWord $phpWord
 * @return FormField[]
 */
function getFormFields(PhpWord $phpWord) {
    return array_reduce(
        $phpWord->getSections(),
        function($fields, Section $section) {
            return array_merge($fields, getFormFieldsRecursive($section));
        },
        []
    );
}

/**
 * @param AbstractElement $element
 * @return FormField[]
 */
function getFormFieldsRecursive(AbstractElement $element) {
    if($element instanceof AbstractContainer) {
        return array_reduce(
            $element->getElements(),
            function($fields, AbstractElement $nestedElement) {
                return array_merge($fields, getFormFieldsRecursive($nestedElement));
            },
            []
        );
    }

    if($element instanceof FormField) {
        return [
            $element->getName() => $element,
        ];
    }

    return [];
}

$phpWord = IOFactory::createReader()->load('/path/to/file');

$fields = getFormFields($phpWord);

$fields['first_name']->setValue('Kuba');
$fields['date']->setValue(Carbon::now()->format('Y-m-d'));

IOFactory::createWriter($phpWord)->save('/path/to/generated-file');
```

**Comment by rabol** [comment]
Hi

I was looking for something to ger the form fields from word, but the above @KKSzymanowski  does not seem to work
[doc_with_form.docx](https://github.com/PHPOffice/PHPWord/files/14084780/doc_with_form.docx)

Attached word have a textbox, combo and a checkbox, but none is detected

What did I miss ?

**Comment by KKSzymanowski** [comment]
After this comment I was messing around with these text fields and decided I'm gonna use PHPWord in a very limited scope. The issue was after I saved the file with fields filled out the formatting was all out of whack.

I only use the XMLReader from PHPWord to open the Word file easier than manually.
Here's the complete class used to read all available form fields and then fill them out with values. Not the cleanest thing I wrote but I'm glad it worked at all because I was under time pressure to deliver this.

https://gist.github.com/KKSzymanowski/acf892616805aed9900289b9bb1ede6d

Keep in mind I only used that for text form fields, may need extending to work for checkboxes or comboboxes.

I use it like this:
```php
$fileName = (new FormFieldHelper($templatePath))
    ->setFieldValues($variables)
    ->save(storage_path($path));
```

`$variables` is an array where keys are the form field names and values are the actual values we want assigned to them.

To get the field names without setting the values I use:
```php
(new FormFieldHelper($templatePath))->getFieldNames();
```

**Comment by Progi1984** [comment]
Superseeded by #2653

**Pull request closed without merging**
